import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { AlertTriangle, Anchor, ArrowRightLeft, Box, CheckCircle2, ClipboardCheck, Map, PackageCheck, Search, Truck, Warehouse } from 'lucide-react'
import { ReceivingCountModal, type CountLine, type CountResultLine, type PlacementLocation } from '../components/ReceivingCountModal'
import { fetchInboundShipments, fetchWarehouseInventory, listWarehouses, postWarehouseReceipt, type InboundShipment, type WarehouseSummary } from '../api/warehouseInventory'
import './WarehouseInventory.css'

const N = (value: number) => new Intl.NumberFormat('en-ET', { maximumFractionDigits: 0 }).format(value)

export default function WarehouseReceiving() {
  const { warehouseId = '' } = useParams(); const navigate = useNavigate()
  const [warehouses, setWarehouses] = useState<WarehouseSummary[]>([]); const [shipments, setShipments] = useState<InboundShipment[]>([])
  const [locations, setLocations] = useState<PlacementLocation[]>([]); const [warehouseName, setWarehouseName] = useState('Warehouse')
  const [selected, setSelected] = useState<InboundShipment | null>(null); const [query, setQuery] = useState('')
  const [sourceFilter, setSourceFilter] = useState<'ALL' | InboundShipment['sourceType']>('ALL')
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null)
  const load = useCallback(async () => { if (!warehouseId) return; setLoading(true); setError(null); try { const [inbound, inventory] = await Promise.all([fetchInboundShipments(warehouseId), fetchWarehouseInventory(warehouseId)]); setShipments(inbound); setWarehouseName(inventory.warehouse.name); setLocations(inventory.locations.filter(location => location.is_active).map(location => ({ id: location.id, code: location.code, name: location.name }))) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not load inbound shipments.') } finally { setLoading(false) } }, [warehouseId])
  useEffect(() => { listWarehouses().then(setWarehouses).catch(() => undefined) }, []); useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [load])
  const visible = useMemo(() => shipments.filter(shipment => (sourceFilter === 'ALL' || shipment.sourceType === sourceFilter) && `${shipment.shipmentNumber} ${shipment.supplierName} ${shipment.waybillNumber ?? ''} ${shipment.truckPlate ?? ''} ${shipment.lines.map(line => `${line.productName} ${line.sku}`).join(' ')}`.toLowerCase().includes(query.toLowerCase())), [shipments, query, sourceFilter])
  const totals = shipments.reduce((sum, shipment) => ({ cartons: sum.cartons + shipment.lines.reduce((s, line) => s + (line.cartonQty ?? 0), 0), units: sum.units + shipment.lines.reduce((s, line) => s + line.quantity, 0), lines: sum.lines + shipment.lines.length }), { cartons: 0, units: 0, lines: 0 })
  async function receive(result: CountResultLine[]) { if (!selected) return; setSaving(true); setError(null); try { await postWarehouseReceipt({ warehouseId, shipment: selected, count: result }); setSelected(null); setNotice(`${selected.shipmentNumber} was reconciled and posted to ${warehouseName}.`); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Receipt could not be posted.') } finally { setSaving(false) } }
  const countLines: CountLine[] = selected?.lines.map(line => ({ shipmentItemId: line.id, productId: line.productId, productName: line.productName, sku: line.sku, expectedQuantity: line.quantity, expectedCartons: line.cartonQty, unitsPerCarton: line.unitsPerCarton, unitOfMeasure: line.unitOfMeasure, assemblyType: line.assemblyType, containerNumber: line.containerNumber })) ?? []
  return <main className="warehouse-inventory-page warehouse-receiving-page">
    <header className="wi-header"><div><Link to={`/warehouse-operations/inventory/${warehouseId}`} className="wi-back">← Warehouse inventory</Link><h1>Receiving dock</h1><p>Unload, count, reconcile the packing list, then place accepted stock.</p></div><div className="wi-header-actions"><select aria-label="Warehouse" value={warehouseId} onChange={event => navigate(`/warehouse-operations/receiving/${event.target.value}`)}>{warehouses.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Link className="wi-button secondary" to={`/warehouse-operations/floor-plan/${warehouseId}?name=${encodeURIComponent(warehouseName)}`}><Map size={16} /> View floor plan</Link><Link className="wi-button primary" to={`/warehouse-operations/inventory/${warehouseId}`}><Box size={16} /> Inventory list</Link></div></header>
    {error && <div className="wi-error"><AlertTriangle size={15} />{error}</div>}{notice && <div className="wr-notice"><CheckCircle2 size={16} />{notice}</div>}
    <section className="wr-guide"><Step number="1" title="Find the truck" copy="Open its shipment and packing list" /><Step number="2" title="Unload & count" copy="Check cartons, units and damage" /><Step number="3" title="Reconcile" copy="Record shortages or overages" /><Step number="4" title="Place & post" copy="Choose floor-plan areas and update stock" /></section>
    <section className="wi-metrics wr-metrics"><Metric icon={<Truck />} label="Inbound loads" value={N(shipments.length)} note="Awaiting warehouse receipt" /><Metric icon={<ClipboardCheck />} label="Packing-list lines" value={N(totals.lines)} note="Products to verify" /><Metric icon={<PackageCheck />} label="Expected cartons" value={N(totals.cartons)} note="Count during unloading" /><Metric icon={<Box />} label="Expected units" value={N(totals.units)} note="Post only what arrived" /></section>
    <section className="wi-panel"><div className="wi-toolbar wr-toolbar"><div className="wi-search"><Search size={16} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search load, waybill, plate, product or SKU" /></div><span className="wr-warehouse-label">Receiving into <b>{warehouseName}</b></span></div><div className="wr-source-tabs" role="tablist" aria-label="Inbound source"><button className={sourceFilter === 'ALL' ? 'active' : ''} onClick={() => setSourceFilter('ALL')}><Truck />All loads <b>{shipments.length}</b></button><button className={sourceFilter === 'SHIPMENT' ? 'active' : ''} onClick={() => setSourceFilter('SHIPMENT')}><Anchor />Direct imports <b>{shipments.filter(item => item.sourceType === 'SHIPMENT').length}</b></button><button className={sourceFilter === 'WAREHOUSE_TRANSFER' ? 'active' : ''} onClick={() => setSourceFilter('WAREHOUSE_TRANSFER')}><ArrowRightLeft />Warehouse transfers <b>{shipments.filter(item => item.sourceType === 'WAREHOUSE_TRANSFER').length}</b></button><button className={sourceFilter === 'ALI_TRANSFER' ? 'active' : ''} onClick={() => setSourceFilter('ALI_TRANSFER')}><Warehouse />From Ali <b>{shipments.filter(item => item.sourceType === 'ALI_TRANSFER').length}</b></button></div>{loading ? <div className="wi-loading">Loading incoming trucks…</div> : <div className="wr-loads">
      {visible.map(shipment => { const cartons = shipment.lines.reduce((sum, line) => sum + (line.cartonQty ?? 0), 0); const units = shipment.lines.reduce((sum, line) => sum + line.quantity, 0); return <article className={`wr-load source-${shipment.sourceType.toLowerCase()}`} key={shipment.id}><div className="wr-load-top"><i>{shipment.sourceType === 'ALI_TRANSFER' ? <Warehouse /> : shipment.sourceType === 'WAREHOUSE_TRANSFER' ? <ArrowRightLeft /> : <Truck />}</i><div><span className="wr-status">{shipment.sourceType === 'ALI_TRANSFER' ? 'FROM ALI / DJIBOUTI' : shipment.sourceType === 'WAREHOUSE_TRANSFER' ? 'WAREHOUSE TRANSFER' : shipment.status.replaceAll('_', ' ')}</span><h2>{shipment.shipmentNumber}</h2><p>{shipment.supplierName}{shipment.eta ? ` · ${new Date(shipment.eta).toLocaleDateString()}` : ''}</p></div><button onClick={() => { setNotice(null); setSelected(shipment) }}>Count & receive</button></div>{(shipment.waybillNumber || shipment.truckPlate || shipment.driverName) && <div className="wr-transport-meta"><span>Waybill <b>{shipment.waybillNumber ?? '—'}</b></span><span>Truck <b>{shipment.truckPlate ?? '—'}</b></span><span>Driver <b>{shipment.driverName ?? '—'}</b></span></div>}<div className="wr-load-stats"><span><small>{shipment.sourceType === 'SHIPMENT' ? 'Packing-list lines' : 'Transfer lines'}</small><b>{shipment.lines.length}</b></span><span><small>Expected cartons</small><b>{cartons ? N(cartons) : '—'}</b></span><span><small>Expected units</small><b>{N(units)}</b></span><span><small>Load mix</small><b>{[...new Set(shipment.lines.map(line => line.assemblyType))].join(' / ')}</b></span></div><div className="wr-line-preview">{shipment.lines.slice(0, 4).map(line => <span key={line.id}><b>{line.productName}</b><small>{line.sku}{line.cartonQty ? ` · ${N(line.cartonQty)} cartons` : ''} · {N(line.quantity)} {line.unitOfMeasure ?? 'units'}</small></span>)}{shipment.lines.length > 4 && <span className="more">+{shipment.lines.length - 4} more lines</span>}</div></article> })}
      {!visible.length && <div className="wi-empty"><Truck /><h2>No inbound loads waiting</h2><p>Loads assigned to this warehouse appear here until they are received.</p></div>}
    </div>}</section>
    <ReceivingCountModal key={selected?.id ?? 'closed'} open={!!selected} title={`Receive ${selected?.shipmentNumber ?? ''}`} subtitle={`Packing-list reconciliation for ${warehouseName}. Only the counted quantity is posted to inventory.`} lines={countLines} locations={locations} saving={saving} error={error} requireCheckoff onCancel={() => setSelected(null)} onSubmit={receive} />
  </main>
}
function Step({ number, title, copy }: { number: string; title: string; copy: string }) { return <div><i>{number}</i><span><b>{title}</b><small>{copy}</small></span></div> }
function Metric({ icon, label, value, note }: { icon: ReactNode; label: string; value: string; note: string }) { return <article><i>{icon}</i><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></article> }
